const countriesData = {
  "_somaliland": { name: "Somaliland", continent: "Africa" },
  "ae": { name: "United Arab Emirates", continent: "Asia" },
  "af": { name: "Afghanistan", continent: "Asia" },
  "al": { name: "Albania", continent: "Europe" },
  "am": { name: "Armenia", continent: "Asia" },
  "ao": { name: "Angola", continent: "Africa" },
  "ar": { name: "Argentina", continent: "Americas" },
  "at": { name: "Austria", continent: "Europe" },
  "au": { name: "Australia", continent: "Oceania" },
  "az": { name: "Azerbaijan", continent: "Asia" },
  "ba": { name: "Bosnia and Herzegovina", continent: "Europe" },
  "bd": { name: "Bangladesh", continent: "Asia" },
  "be": { name: "Belgium", continent: "Europe" },
  "bf": { name: "Burkina Faso", continent: "Africa" },
  "bg": { name: "Bulgaria", continent: "Europe" },
  "bi": { name: "Burundi", continent: "Africa" },
  "bj": { name: "Benin", continent: "Africa" },
  "bn": { name: "Brunei", continent: "Asia" },
  "bo": { name: "Bolivia", continent: "Americas" },
  "br": { name: "Brazil", continent: "Americas" },
  "bs": { name: "Bahamas", continent: "Americas" },
  "bt": { name: "Bhutan", continent: "Asia" },
  "bw": { name: "Botswana", continent: "Africa" },
  "by": { name: "Belarus", continent: "Europe" },
  "bz": { name: "Belize", continent: "Americas" },
  "ca": { name: "Canada", continent: "Americas" },
  "cd": { name: "DR Congo", continent: "Africa" },
  "cf": { name: "Central African Republic", continent: "Africa" },
  "cg": { name: "Republic of the Congo", continent: "Africa" },
  "ch": { name: "Switzerland", continent: "Europe" },
  "ci": { name: "Ivory Coast", continent: "Africa" },
  "cl": { name: "Chile", continent: "Americas" },
  "cm": { name: "Cameroon", continent: "Africa" },
  "cn": { name: "China", continent: "Asia" },
  "co": { name: "Colombia", continent: "Americas" },
  "cr": { name: "Costa Rica", continent: "Americas" },
  "cu": { name: "Cuba", continent: "Americas" },
  "cv": { name: "Cape Verde", continent: "Africa" },
  "cy": { name: "Cyprus", continent: "Asia" },
  "cz": { name: "Czech Republic", continent: "Europe" },
  "de": { name: "Germany", continent: "Europe" },
  "dj": { name: "Djibouti", continent: "Africa" },
  "dk": { name: "Denmark", continent: "Europe" },
  "dm": { name: "Dominica", continent: "Americas" },
  "do": { name: "Dominican Republic", continent: "Americas" },
  "dz": { name: "Algeria", continent: "Africa" },
  "ec": { name: "Ecuador", continent: "Americas" },
  "ee": { name: "Estonia", continent: "Europe" },
  "eg": { name: "Egypt", continent: "Africa" },
  "er": { name: "Eritrea", continent: "Africa" },
  "es": { name: "Spain", continent: "Europe" },
  "et": { name: "Ethiopia", continent: "Africa" },
  "fi": { name: "Finland", continent: "Europe" },
  "fk": { name: "Falkland Islands", continent: "Americas" },
  "fr": { name: "France", continent: "Europe" },
  "ga": { name: "Gabon", continent: "Africa" },
  "gb": { name: "United Kingdom", continent: "Europe" },
  "ge": { name: "Georgia", continent: "Asia" },
  "gh": { name: "Ghana", continent: "Africa" },
  "gl": { name: "Greenland", continent: "Americas" },
  "gm": { name: "Gambia", continent: "Africa" },
  "gn": { name: "Guinea", continent: "Africa" },
  "gq": { name: "Equatorial Guinea", continent: "Africa" },
  "gr": { name: "Greece", continent: "Europe" },
  "gt": { name: "Guatemala", continent: "Americas" },
  "gw": { name: "Guinea-Bissau", continent: "Africa" },
  "gy": { name: "Guyana", continent: "Americas" },
  "hn": { name: "Honduras", continent: "Americas" },
  "hr": { name: "Croatia", continent: "Europe" },
  "ht": { name: "Haiti", continent: "Americas" },
  "hu": { name: "Hungary", continent: "Europe" },
  "id": { name: "Indonesia", continent: "Asia" },
  "ie": { name: "Ireland", continent: "Europe" },
  "il": { name: "Israel", continent: "Asia" },
  "in": { name: "India", continent: "Asia" },
  "iq": { name: "Iraq", continent: "Asia" },
  "ir": { name: "Iran", continent: "Asia" },
  "is": { name: "Iceland", continent: "Europe" },
  "it": { name: "Italy", continent: "Europe" },
  "jm": { name: "Jamaica", continent: "Americas" },
  "jo": { name: "Jordan", continent: "Asia" },
  "jp": { name: "Japan", continent: "Asia" },
  "ke": { name: "Kenya", continent: "Africa" },
  "kg": { name: "Kyrgyzstan", continent: "Asia" },
  "kh": { name: "Cambodia", continent: "Asia" },
  "km": { name: "Comoros", continent: "Africa" },
  "kp": { name: "North Korea", continent: "Asia" },
  "kr": { name: "South Korea", continent: "Asia" },
  "kw": { name: "Kuwait", continent: "Asia" },
  "kz": { name: "Kazakhstan", continent: "Asia" },
  "la": { name: "Laos", continent: "Asia" },
  "lb": { name: "Lebanon", continent: "Asia" },
  "lc": { name: "Saint Lucia", continent: "Americas" },
  "lk": { name: "Sri Lanka", continent: "Asia" },
  "lr": { name: "Liberia", continent: "Africa" },
  "ls": { name: "Lesotho", continent: "Africa" },
  "lt": { name: "Lithuania", continent: "Europe" },
  "lu": { name: "Luxembourg", continent: "Europe" },
  "lv": { name: "Latvia", continent: "Europe" },
  "ly": { name: "Libya", continent: "Africa" },
  "ma": { name: "Morocco", continent: "Africa" },
  "md": { name: "Moldova", continent: "Europe" },
  "me": { name: "Montenegro", continent: "Europe" },
  "mg": { name: "Madagascar", continent: "Africa" },
  "mk": { name: "North Macedonia", continent: "Europe" },
  "ml": { name: "Mali", continent: "Africa" },
  "mm": { name: "Myanmar", continent: "Asia" },
  "mn": { name: "Mongolia", continent: "Asia" },
  "mr": { name: "Mauritania", continent: "Africa" },
  "mt": { name: "Malta", continent: "Europe" },
  "mu": { name: "Mauritius", continent: "Africa" },
  "mv": { name: "Maldives", continent: "Asia" },
  "mw": { name: "Malawi", continent: "Africa" },
  "mx": { name: "Mexico", continent: "Americas" },
  "my": { name: "Malaysia", continent: "Asia" },
  "mz": { name: "Mozambique", continent: "Africa" },
  "na": { name: "Namibia", continent: "Africa" },
  "nc": { name: "New Caledonia", continent: "Oceania" },
  "ne": { name: "Niger", continent: "Africa" },
  "ng": { name: "Nigeria", continent: "Africa" },
  "ni": { name: "Nicaragua", continent: "Americas" },
  "nl": { name: "Netherlands", continent: "Europe" },
  "no": { name: "Norway", continent: "Europe" },
  "np": { name: "Nepal", continent: "Asia" },
  "nz": { name: "New Zealand", continent: "Oceania" },
  "om": { name: "Oman", continent: "Asia" },
  "pa": { name: "Panama", continent: "Americas" },
  "pe": { name: "Peru", continent: "Americas" },
  "pg": { name: "Papua New Guinea", continent: "Oceania" },
  "ph": { name: "Philippines", continent: "Asia" },
  "pk": { name: "Pakistan", continent: "Asia" },
  "pl": { name: "Poland", continent: "Europe" },
  "pr": { name: "Puerto Rico", continent: "Americas" },
  "pt": { name: "Portugal", continent: "Europe" },
  "py": { name: "Paraguay", continent: "Americas" },
  "qa": { name: "Qatar", continent: "Asia" },
  "ro": { name: "Romania", continent: "Europe" },
  "rs": { name: "Serbia", continent: "Europe" },
  "ru": { name: "Russia", continent: "Europe" },
  "rw": { name: "Rwanda", continent: "Africa" },
  "sa": { name: "Saudi Arabia", continent: "Asia" },
  "sb": { name: "Solomon Islands", continent: "Oceania" },
  "sc": { name: "Seychelles", continent: "Africa" },
  "sd": { name: "Sudan", continent: "Africa" },
  "se": { name: "Sweden", continent: "Europe" },
  "sg": { name: "Singapore", continent: "Asia" },
  "si": { name: "Slovenia", continent: "Europe" },
  "sk": { name: "Slovakia", continent: "Europe" },
  "sl": { name: "Sierra Leone", continent: "Africa" },
  "sn": { name: "Senegal", continent: "Africa" },
  "so": { name: "Somalia", continent: "Africa" },
  "sr": { name: "Suriname", continent: "Americas" },
  "ss": { name: "South Sudan", continent: "Africa" },
  "st": { name: "Sao Tome and Principe", continent: "Africa" },
  "sv": { name: "El Salvador", continent: "Americas" },
  "sy": { name: "Syria", continent: "Asia" },
  "sz": { name: "Eswatini", continent: "Africa" },
  "td": { name: "Chad", continent: "Africa" },
  "tg": { name: "Togo", continent: "Africa" },
  "th": { name: "Thailand", continent: "Asia" },
  "tj": { name: "Tajikistan", continent: "Asia" },
  "tm": { name: "Turkmenistan", continent: "Asia" },
  "tn": { name: "Tunisia", continent: "Africa" },
  "tr": { name: "Turkey", continent: "Asia" },
  "tt": { name: "Trinidad and Tobago", continent: "Americas" },
  "tw": { name: "Taiwan", continent: "Asia" },
  "tz": { name: "Tanzania", continent: "Africa" },
  "ua": { name: "Ukraine", continent: "Europe" },
  "ug": { name: "Uganda", continent: "Africa" },
  "us": { name: "United States", continent: "Americas" },
  "uy": { name: "Uruguay", continent: "Americas" },
  "uz": { name: "Uzbekistan", continent: "Asia" },
  "vc": { name: "Saint Vincent and the Grenadines", continent: "Americas" },
  "ve": { name: "Venezuela", continent: "Americas" },
  "vn": { name: "Vietnam", continent: "Asia" },
  "vu": { name: "Vanuatu", continent: "Oceania" },
  "ye": { name: "Yemen", continent: "Asia" },
  "za": { name: "South Africa", continent: "Africa" },
  "zm": { name: "Zambia", continent: "Africa" },
  "zw": { name: "Zimbabwe", continent: "Africa" }
};
window.countriesData = countriesData;
